### ISSUE TITLE
Missing () on call.

### ISSUE THREAD

**Issue by PySimpleGUI** [XavierTheCreator/PythonSwissArmyKnife#1]
https://github.com/XavierTheCreator/PythonSwissArmyKnife/blob/670a876751415ff03d83200f6478848bdceff6fd/main.py#L32

Need to add () after your call to `window.refresh`

**Comment by PySimpleGUI** [comment]
You can remove that call.  It doesn't do anything because the very next statement you execute is `window.read()`.

What you needed was something that allowed you to do the download while still able to update your GUI.  That's not possible without using threading, which is that another issue does.  If there is a callback of some kind that the download package makes on a periodic basis, then you could add a refresh in there.

**Comment by XavierTheCreator** [comment]
Line has been removed. I'm currently going through the issues and making updates.  Thanks a lot by the way
