### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by PySimpleGUI** [XavierTheCreator/PythonSwissArmyKnife#4]
Add your screenshot to your readme.  You can upload it into an issue, like this:

![image](https://user-images.githubusercontent.com/46163555/99821908-998c7900-2b20-11eb-96a3-bda5780a485a.png)

And then add this line into your readme.md file to show the screenshot on your main github page to embed this image into your readme:
```
![image](https://user-images.githubusercontent.com/46163555/99821908-998c7900-2b20-11eb-96a3-bda5780a485a.png)
```

**Comment by XavierTheCreator** [comment]
added
